name: publish
on:
  push:
    branches: [main]
    paths:
      - "packages/*/CHANGELOG.md"
      - "packages/*/Releases.md"
      - "Releases.md"
      - "CHANGELOG.md"
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: deno publish
